### PR TITLE
Chronos check for Sensu

### PR DESCRIPTION
**Pull request by seanmcl**
This is a check for Chronos, similar to the other Mesosphere projects,
Mesos, and Marathon.  Chronos doesn't have a generic health endpoint
like /ping for mesos, so we query the job graph at /scheduler/jobs.

I manually tested running and non-running chronos. Though unit tests
would be preferable, mocking the Mesos infrastructure will be a
separate commit.

### CODE REVIEW

**Comment by mattyjones** [comment]
@seanmcl 
Thanks for this.  Can you also update the Changelog as well please, then I will merge this is an cut a release.

Thanks!

**Comment by seanmcl** [comment]
Done.  I changed "Unreleased][unreleased]" to "Unreleased".  I wasn't sure of the purpose of the brackets, as they didn't format in markdown.  

Thanks for the quick turnaround!

**Comment by mattyjones** [comment]
@seanmcl  Can you please rebase this so we can do a clean merge.

Thanks

**Comment by seanmcl** [comment]
I closed this with the misguided idea that I could rebase it on top of another branch in my own fork that was also pending review.  The PR ended up in my own fork (sigh).  Since I couldn't reopen this, I created a new one.

**Pull request closed without merging**
