### PR TITLE
Update endpoint for newer mesos verions

### PR DESCRIPTION
**Pull request by runningman84**
## Pull Request Checklist

https://github.com/sensu-plugins/sensu-plugins-mesos/issues/7
#### General
- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [ ] Update README with any necessary configuration snippets
- [X] RuboCop passes
- [X] Existing tests pass 
#### Purpose

Fixes compatablity with latest mesos release
#### Known Compatablity Issues

Will not work with older verions

### CODE REVIEW

**Comment by eheydrick** [comment]
Would it be possible to maintain compatibility with the previous endpoint? Maybe detect the version and use the appropriate endpoint.

**Comment by runningman84** [comment]
Checking the version would need an additional api call. Maybe we could just do "try newVersion catch... try oldVersion..." this would reduce the performance impact in the future and still maintain backward compatibility.

**Comment by luisdavim** [comment]
Hi, any updates on this? maybe if we pass the uri as an option and use /metrics/snapshot as the default value it would work by default for new version and you can still make it work for older versions by passing the uri....

**Comment by runningman84** [comment]
No I haven't used mesos lateley feel free to modify it. From my point of view we should just drop support for old mesos releases...

**Comment by majormoses** [comment]
@runningman84 how old are we talking? While I in general tend to agree with not keeping super old versions lying around there has been nothing to indicate how old and what it's support lifecycle is. If it's still supported by messos then we should support it if possible which seems very doable here by passing in an option as suggested by @luisdavim.

**Comment by majormoses** [comment]
closing in favor of #15

**Pull request closed without merging**
